### ISSUE TITLE
NEWS file

### ISSUE THREAD

**Issue by kasperdanielhansen** [HenrikBengtsson/illuminaio#23]
Our NEWS file was recently moved to NEWS.md. Got the following email from Lori Kern:

> As we are preparing for the Bioconductor release, we are having trouble with the illuminaio NEWS file.  I think the problem occurs because there seems to be 2 news entries that do not have consistent versioning with the rest of the file.  there are entries for a version 3.24.0 and 3.22.0  - considering the package version is still 0.x.y these seem to be in error.  Could you please investigate and fix.

**Comment by kasperdanielhansen** [comment]
This is from `NEWS.md` in the git repos on Bioconductor

```
  38
     39 # Version 3.24.0 [2021-05-19]
     40
     41  * The version number was bumped for the Bioconductor release version,
     42    which is now BioC 3.13 for R (>= 4.0.3).
     43
     44
     45 # Version 3.22.0 [2020-10-27]
     46
     47  * The version number was bumped for the Bioconductor release version,
     48    which is now BioC 3.12 for R (>= 4.0.0).
     49
 ```
 These lines are absent from Github

**Comment by kasperdanielhansen** [comment]
Seems like we need to push upstream.

**Comment by HenrikBengtsson** [comment]
Got it. Yes, this was fixed in the develop branch (https://github.com/HenrikBengtsson/illuminaio/commit/d730d1a354e1508802b72b1be0e13b6725f89762). I'll merge into master and push to Bioc devel

**Comment by HenrikBengtsson** [comment]
Pushed v0.39.2 to Bioc devel
