### ISSUE TITLE
package installs but library doesn't load

### ISSUE THREAD

**Issue by mistrm82** [HenrikBengtsson/illuminaio#3]
library(illuminaio)

Error in FUN("readIDAT"[[1L]], ...) : 
  lazy-load database '/home/mistrm82/R/x86_64-pc-linux-gnu-library/3.1/illuminaio/R/illuminaio.rdb' is corrupt
In addition: Warning messages:
1: In FUN("readIDAT"[[1L]], ...) :
  restarting interrupted promise evaluation
2: In FUN("readIDAT"[[1L]], ...) : internal error -3 in R_decompress1

sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by ttriche** [comment]
Restart your R session and try loading the library again.  Most likely you installed the GitHub repo over top of your BioC installation of the package ( or vice versa ) hence the error message. 

This often, but not always, occurs when you overwrite a package that has been loaded and then try to call functions in that same namespace which hook into the new code.  I'm pretty sure it's an issue with the byte compiled version no longer having all the same signatures as the previous byte compiled version that was overwritten.  One of these days I will get around to testing this theory. 

Meanwhile, try the same commands in a new session and please report if you continue to have the same issue. 

Best,

--t

**Comment by mistrm82** [comment]
A simple restart was the solution. Thank you!
