### ISSUE TITLE
readBPM(): Hard-coded seek() jump?!?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/illuminaio#6]
This is related to Issue #5. I just looked at the code for `readBPM()` and there is [piece of code](https://github.com/HenrikBengtsson/illuminaio/blob/develop/R/readBPM.R#L76-L88) that looks weird and very unsafe to me:

``` r
    if (FALSE) {
        snpIndexByteOffset <- seek(con)
        snpIndex <- readInt(con, n=nEntries)
        ## for the 1M array, these are simply in order from 1 to 1072820.

        snpNamesByteOffset <- seek(con)
        snpNames <- rep("A", times=nEntries)
        for(i1 in 1:nEntries){
            snpNames[i1] <- readString(con)
        }
    }

    seek(con, where=15278138L)
```

That `seek()` is particularly scary to me.

Does any one know where this originates from and the rationale behind it?  I don't know who wrote `readBPM()` in the first place.

**Comment by HenrikBengtsson** [comment]
Hmm... looking at [humanmethylation450_15017482_v-1-2.bpm](ftp://webdata:webdata@ussd-ftp.illumina.com/downloads/ProductFiles/HumanMethylation450/humanmethylation450_15017482_v-1-2.bpm), a BPM file is more or less comma-separated plain-text data, whereas the code suggests it is binary.  Also, from code inspection I'm pretty sure `readBPM()` is not doing anything useful.  I would declare it non-functional and should not be used by anyone.  

I'm leaving it at this for now.

@kasperdanielhansen, comment?

**Comment by kasperdanielhansen** [comment]
I don't know who wrote it either and I don't think it is really supported.
Also, in my experience, Illumina always releases CSV versions of their BPM
files on their websites.  But I am mostly familiar with their methylation
arrays.

Best,
Kasper

**Comment by ttriche** [comment]
Keith Baggerly wrote it initially

--t

On Tue, Jan 12, 2016 at 10:49 AM, Henrik Bengtsson <notifications@github.com

**Comment by ttriche** [comment]
oh, readBPM not readIDAT.. agreed

BPMs are a horrid little wrapper around a CSV

--t

On Tue, Jan 12, 2016 at 11:28 AM, Henrik Bengtsson <notifications@github.com

**Comment by ttriche** [comment]
I haven't seen an example lately where they didn't provide a CSV, and in
any event, a few quick ninja edits in vim turns a BPM into a CSV

--t

**Comment by HenrikBengtsson** [comment]
I've [deprecated `readBPM()`](https://github.com/HenrikBengtsson/illuminaio/commit/fe1da3e60ec5a9a56b60922b2d9f4780fd1bc09f) in the GitHub `develop` branch.  If there's time, it could be brought back later, but as I see it, no one should use this function.

Do you agree?  If so, I merge it into the `master` branch and then push it to Bioc devel.

**Comment by ttriche** [comment]
+1 from me, Kasper will have to intone on his end

**Comment by kasperdanielhansen** [comment]
Agreed. I have never used it and I'm not really willing to support it. And as far as I can see if is unnecessary. 

Best,
Kasper
(Sent from my phone.)

**Comment by HenrikBengtsson** [comment]
illuminaio 0.13.1 pushed to Bioc devel.
