### ISSUE TITLE
Accessing Control Signal

### ISSUE THREAD

**Issue by RaphaelRaphael** [HenrikBengtsson/illuminaio#7]
Hi !

I have a 450K IDAT file and I want to access the signal of the control probes.
Some of them seems not accessible after readIDAT :+1: 
`
 Green=readIDAT(paste(basenames[1],"_Grn.idat",sep=""))$Quants[,"Mean"]
`
Here I take the first probe address from the Manifest :
`Green["21630339"]`
giving me a NA

While the second one : 
`Green["27630314"]`
Is ok...

Do you see a reason for that ?

Thank you !

**Comment by RaphaelRaphael** [comment]
Here my code solving the problem in my context:

  `probeInfo=probeInfo[(probeInfo$Address != "21630339" & probeInfo$Address != "24669308"),]`

Two of the control probes are not in the IDAT file.

**Comment by kasperdanielhansen** [comment]
I think this solves your question.  But why do you think these two probes
should be on the array?

**Comment by RaphaelRaphael** [comment]
Both are in the Manifest file :

[Controls],,,,
**21630339**,STAINING,-99,DNP(20K),
27630314,STAINING,Red,DNP (High),
43603326,STAINING,Purple,DNP (Bkg),
41666334,STAINING,Green,Biotin (High),
**24669308**,STAINING,-99,Biotin(5K),
34648333,STAINING,Blue,Biotin (Bkg),
63642461,EXTENSION,Red,Extension (A),
47640365,EXTENSION,Purple,Extension (T)
`

**Comment by kasperdanielhansen** [comment]
Its been a while since I looked at this, but I agree with you: the manifest
contains control probes not on the array.

**Comment by HenrikBengtsson** [comment]
Was this one resolved or is there something that needs to be fixed in illuminaio?

**Comment by ttriche** [comment]
anything with -99 as the color is either not on the production arrays or is
reserved for later use.  Found this out the hard way a long time ago.  Will
probably provide some extra fun on the 850k arrays too.

--t

**Comment by kasperdanielhansen** [comment]
Henrik, it's all good.  There was an error in an annotation file from
Illumina which refers to probe identifiers ("addresses") which were not
present on the array itself ... kind of weird.

Best,
Kasper

**Comment by ttriche** [comment]
Right, I should have been explicit -- this is an error in annotation, not in illuminaio. 

--t
